sudo: required

language: node_js

node_js:
  - "0.10.40"

os:
  - linux
  - osx

install:
  - npm install
  - sudo curl http://install.meteor.com | /bin/sh
  - node --version
  - meteor --version

script:
  - node make.js test.cover.send
